### ISSUE TITLE
背景图片有时候会消失，需要多映射一个目录

### ISSUE THREAD

**Issue by lovemikusama** [Heavrnl/nexus-terminal#36]
docker部署，使用的时候发现背景图片有时候会消失，backend多映射一个`/app/uploads/backgrounds`目录就好了

```yml
  backend:
    image: heavrnl/nexus-terminal-backend:latest
    container_name: nexus-terminal-backend
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3001
    volumes:
      - ./data:/app/data
      - ./backgrounds:/app/uploads/backgrounds
    networks:
      - nexus-terminal-network
```
